services:

  mongodb:
    image: mongo:8
    container_name: devflow-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: ./server
    container_name: devflow-backend
    ports:
      - "10000:10000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongodb:27017/devflow
      JWT_SECRET: devflow-secret-key
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: devflow-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus:latest
    container_name: devflow-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: devflow-grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  mongodb_data: